name: test-flow

on:
  push:
    branches: [ prod, stg, dev ]

jobs:
    prepare:
        name: Prepare
        runs-on: ubuntu-latest
        outputs:
            envs: ${{ steps.matrix.outputs.envs }}
        steps:
            - name: matrix
              id: matrix
              run: |
                envs=$(echo '["dev","stg","prod"]' | jq -c)
            - name: Install dependencies
              run: echo "Installing dependencies"
    build:
        uses: ./.github/workflows/build.yml
        