name: test-flow

on:
  push:
    branches: [ prod, stg, dev ]

jobs:
    prepare:
        name: Prepare
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install dependencies
              run: echo "Installing dependencies"
    build:
        uses: ./.github/workflows/build.yml
        